cors:
  enabled: false
  allowed-headers: "*"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS
  allowed-origins: "*"
  exposed-headers: Content-Disposition, Content-Length, Content-Type

endpoints:
  api1:
    base-url: http://localhost:8080/
    password: 1234
    username: user1@mail.com

feign:
  #The next attributes are handled manually, as there is a bug when setting timeouts and disabling follow redirects
  connectTimeout: 5000
  readTimeout: 5000
  followRedirects: false
  ignore-ssl: false
  #end
  client.config:
    default:
      loggerLevel: BASIC
  compression:
    request.enabled: true
    response.enabled: true
  okhttp.enabled: true

info:
  app:
    name: ${name}
    description: ${description}
    version: ${version}
    id: ID-99999

jwt:
  expiration: 18000000
  header: Authorization
  refresh-expiration: 18000000000000
  secret: "!\$V?GLhtdE}HgLBkYnRw%YfJ\$dM7,DP\$6;E3T_xV28cU7D}Vwr;!TP4Nj.da" # Put secure hash here
  tokenPrefix: Bearer

locale:
  default: en-US

logging:
  config: classpath:logs/log4j2-spring.xml

management:
  endpoint:
    info.enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /_monitor


server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  error:
    whitelabel:
      enabled: false
  port: 8080

spring:
  application:
    name: apitemplate
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
  http:
    encoding:
      charset: UTF-8
      force: true
  flyway:
    enabled: false
  jmx:
    enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        proc:
          param_null_passing: true
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
  mvc:
    throw-exception-if-no-handler-found: true
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: ${env}
  resources:
    add-mappings: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 6MB

springdoc:
  show-actuator: true
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
