FROM quay.io/maksymbilenko/oracle-12c

ADD src/main/resources/db/migration/*.sql /docker-entrypoint-initdb.d/

ADD docker/contents/V0__user.sql /docker-entrypoint-initdb.d/
ADD docker/contents/V999__delete.sh /docker-entrypoint-initdb.d/