CREATE TABLE TEMPLATE."ROLE" (
    ID INTEGER NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE TIMESTAMP,
    ACTIVE CHAR(1) DEFAULT '1' NOT NULL,
    CONSTRAINT ROLE_PK PRIMARY KEY (ID)
);
CREATE SEQUENCE TEMPLATE.role_seq START WITH 1;

CREATE TABLE TEMPLATE."GROUP" (
    ID INTEGER NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    CREATION_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE TIMESTAMP,
    ACTIVE CHAR(1) DEFAULT '1' NOT NULL,
    CONSTRAINT USER_GROUP_PK PRIMARY KEY (ID)
);
CREATE SEQUENCE TEMPLATE.group_seq START WITH 1;

CREATE TABLE TEMPLATE."USER" (
    ID INTEGER NOT NULL,
    NAME VARCHAR2(50) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL,
    PASSWORD VARCHAR2(150) NOT NULL,
    GROUP_ID INT NOT NULL,
    BALANCE NUMBER(19,4) NULL,
    CREATION_DATE TIMESTAMP DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE TIMESTAMP,
    ACTIVE CHAR(1) DEFAULT '1' NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (ID),
    CONSTRAINT USER_EMAIL_UN UNIQUE (EMAIL),
    CONSTRAINT USER_GROUP_FK FOREIGN KEY (GROUP_ID) REFERENCES "GROUP" (ID)
);
CREATE SEQUENCE TEMPLATE.user_seq START WITH 1;

CREATE TABLE TEMPLATE.USER_ROLE (
    USER_ID INTEGER NOT NULL,
    ROLE_ID INTEGER NOT NULL,
    CONSTRAINT USER_ROLE_PK PRIMARY KEY (USER_ID, ROLE_ID)
);

insert into TEMPLATE."ROLE" (id, name) values (TEMPLATE.role_seq.NEXTVAL, 'Role 1');
insert into TEMPLATE."ROLE" (id, name) values (TEMPLATE.role_seq.NEXTVAL, 'Role 2');
insert into TEMPLATE."ROLE" (id, name) values (TEMPLATE.role_seq.NEXTVAL, 'Role 3');
insert into TEMPLATE."ROLE" (id, name) values (TEMPLATE.role_seq.NEXTVAL, 'Role 4');

insert into TEMPLATE."GROUP" (id, name) values (TEMPLATE.group_seq.NEXTVAL, 'Group 1');
insert into TEMPLATE."GROUP" (id, name) values (TEMPLATE.group_seq.NEXTVAL, 'Group 2');
insert into TEMPLATE."GROUP" (id, name) values (TEMPLATE.group_seq.NEXTVAL, 'Group 4');
insert into TEMPLATE."GROUP" (id, name) values (TEMPLATE.group_seq.NEXTVAL, 'Group 3');
